
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

CONSOLE_ENABLE = no
LTO_ENABLE = yes

LIB_SRC += local_init.c local_oled.c local_general.c

